# Generated by Django 4.1.2 on 2022-10-14 11:15
from django.db import migrations
from static_data import values_for_db
import sys

location_csv = 'singapore_locations.csv'

def add_locations(apps, schema_editor):
    Location = apps.get_model('tutorbook', 'Location')
    locations = values_for_db(location_csv)
    for location in locations:
        new_entry = Location(location_name=location)
        new_entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tutorbook', '0002_location_tutor'),
    ]

    operations = [
        migrations.RunPython(add_locations)
    ]
