# Generated by Django 4.1.2 on 2022-10-14 15:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutorbook.user_type')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('looking_for_assignment', models.BooleanField(default=False)),
                ('about_me', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField()),
                ('subscription_expires_at', models.DateTimeField()),
                ('level', models.ManyToManyField(to='tutorbook.level')),
                ('location', models.ManyToManyField(to='tutorbook.location')),
                ('subject', models.ManyToManyField(to='tutorbook.subject')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorbook.user')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_one', to='tutorbook.user')),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_two', to='tutorbook.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.DecimalValidator(2, 1)])),
                ('tutor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutorbook.tutor')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorbook.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver_id', to='tutorbook.user')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender_id', to='tutorbook.user')),
                ('thread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorbook.thread')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorbook.user')),
            ],
        ),
    ]
