# Generated by Django 4.1.2 on 2022-10-14 11:15
from django.db import migrations
from static_data import values_for_db
import sys

location_csv = 'singapore_locations.csv'
user_types_csv = 'user_types.csv'
subjects_csv = 'subjects.csv'
levels_csv = 'levels.csv'


def add_initial_data(apps, schema_editor):
    def delete_data_present(Model):
        Model.objects.all().delete()

    def add_table_rows(arr, Model, attribute_name):
        Model_to_access = apps.get_model('tutorbook', Model)
        for item in arr:
            key_pair = {attribute_name: item}
            Model_to_access.objects.get_or_create(**key_pair)

    locations = values_for_db(location_csv)
    user_types = values_for_db(user_types_csv)
    subjects = values_for_db(subjects_csv)
    levels = values_for_db(levels_csv)
    add_table_rows(locations, 'Location', 'location_name')
    add_table_rows(user_types, 'User_Type', 'type_name')
    add_table_rows(subjects, 'Subject', 'subject_name')
    add_table_rows(levels, 'Level', 'level_name')


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbook', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data)
    ]
