# Generated by Django 4.1.2 on 2022-10-14 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('looking_for_assignment', models.BooleanField(default=False)),
                ('about_me', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField()),
                ('subscription_expires_at', models.DateTimeField()),
                ('location', models.ManyToManyField(to='tutorbook.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorbook.user')),
            ],
        ),
    ]
