# Generated by Django 4.1.2 on 2022-10-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbook', '0002_auto_20221014_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img_url',
            field=models.URLField(default='https://i.stack.imgur.com/l60Hf.png'),
        ),
    ]
