# Generated by Django 4.1.2 on 2022-10-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbook', '0002_location_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='level',
            field=models.ManyToManyField(to='tutorbook.level'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='subject',
            field=models.ManyToManyField(to='tutorbook.subject'),
        ),
    ]
