# Generated by Django 4.1.2 on 2022-10-14 13:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbook', '0003_level_subject_tutor_level_tutor_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_one', to='tutorbook.user')),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_two', to='tutorbook.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.DecimalValidator(2, 1)])),
                ('tutor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutorbook.tutor')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorbook.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver_id', to='tutorbook.user')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender_id', to='tutorbook.user')),
                ('thread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorbook.thread')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorbook.user')),
            ],
        ),
    ]
