# Generated by Django 4.1.2 on 2022-10-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbook', '0004_rename_user_id_tutor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='about_me',
            field=models.TextField(null=True),
        ),
    ]
