# Generated by Django 4.1.2 on 2022-10-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbook', '0005_alter_tutor_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='has_unread',
            field=models.BooleanField(default=True),
        ),
    ]
