# Generated by Django 4.1.2 on 2022-10-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbook', '0006_message_is_read_thread_has_unread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='level',
            new_name='levels',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='location',
            new_name='locations',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='subject',
            new_name='subjects',
        ),
    ]
