# Generated by Django 4.1.2 on 2022-10-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbook', '0010_review_review_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='tutor_id',
            new_name='tutor',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
