# Generated by Django 4.1.2 on 2022-10-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbook', '0011_rename_tutor_id_review_tutor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='user_one',
        ),
        migrations.AddField(
            model_name='thread',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutorbook.tutor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thread',
            name='user_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutorbook.user'),
        ),
    ]
