# Generated by Django 4.1.2 on 2022-10-17 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbook', '0014_rename_receiver_id_message_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tutor_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
