# Generated by Django 4.1.2 on 2022-10-17 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbook', '0015_tutor_tutor_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
