# Generated by Django 4.1.2 on 2022-10-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbook', '0016_assignment_assignment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img_url',
            field=models.URLField(null=True),
        ),
    ]
