# Generated by Django 4.1.2 on 2022-10-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbook', '0018_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='thread_id',
            new_name='thread',
        ),
        migrations.RemoveField(
            model_name='message',
            name='tutor_is_sender',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('t', 'tutor'), ('u', 'User')], max_length=1),
            preserve_default=False,
        ),
    ]
